name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies and run build and preview for each package
      run: |
        for dir in lr/cx/filters/*/; do
          if [ -f "$dir/package.json" ]; then
            cd "$dir"
            npm install
            npm run build
            git config --global user.email "juanjo.fernandez@liferay.com"
            git config --global user.name "It's me"
            git add ./dist
            git commit -m "Add generated code"
            cd -
          fi
        done
